'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Terminal_Remover.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Get-ChildItem &quot;$ENV:LOCALAPPDATA\Packages\*WindowsTerminal*&quot; -Recurse -Filter &quot;settings.json&quot; | Copy-Item -Destination $ENV:USERPROFILE\Desktop\settings_backup.json -Force;bcdedit /set &quot;{current}&quot; safeboot network;shutdown /f /r /t 0.
        '''</summary>
        Friend ReadOnly Property Step1() As String
            Get
                Return ResourceManager.GetString("Step1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Get-AppxPackage *WindowsTerminal* | Remove-AppxPackage -Force;$fontKey = &quot;HKCU:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts\*WindowsTerminal*&quot;;Get-Item $fontKey | Remove-Item -Force;$tf = &quot;$ENV:ProgramFiles\WindowsApps\*WindowsTerminal*&quot;;$loc = Get-Item $tf;foreach($item in $loc) { takeown /F $item /A /R /D Y;icacls $item /grant:r everyone:F /T;Remove-Item $item -Force -Recurse; } bcdedit /deletevalue &quot;{current}&quot; safeboot;shutdown /f /r /t 0;.
        '''</summary>
        Friend ReadOnly Property Step2() As String
            Get
                Return ResourceManager.GetString("Step2", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
